name: bot

on: 
  issue_comment:
    types:
      - created
jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - uses: elm-expert/actions/bot@latest
        with:
          users: HairyRabbit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
